### ISSUE TITLE
getUserTweets -- TypeError:  Cannot read properties of undefined (reading 'instructions')

### ISSUE THREAD

**Issue by vincanger** [Rishikant181/Rettiwt-API#311]
this method has been working fine for a week or so, and just started throwing a TypeError the past day or so. I am able to get the user details, but not the user's tweets anymore

```
error TypeError: Cannot read properties of undefined (reading 'instructions')
 at Object.extractUserTweets
 ```

**Comment by Rishikant181** [comment]
Seems like Twitter just removed functionality to browse Twitter without having an account.

**Comment by vincanger** [comment]
nooooooo

**Comment by vincanger** [comment]
@Rishikant181 it seems like even after logging in and initializing the client with cookies, `getUserTweets` still doesn't work. Could it be they changed up more than that?

**Comment by Rishikant181** [comment]
That's because, even if you do login, ```getUserTweets``` still ignores that and just tries to fetch tweets without logging in. This was intended behavior, since I wanted to keep the methods that use login and those that don't, separate.

If are willing to fetch tweets with logging in, use [this](https://rishikant181.github.io/Rettiwt-API/classes/TweetService.html#getTweets) method instead.

**Comment by Rishikant181** [comment]
@vincanger I have opened up an issue (see #312) regarding all functions requiring logging in. I'll be doing some testing against Twitter these two days. You may expect to see changes by Tuesday. 

I apologize for the inconvenience.

**Comment by Rishikant181** [comment]
@vincanger Please update to the latest version.
