### ISSUE TITLE
Get friendship between 2 users

### ISSUE THREAD

**Issue by Proxu-s** [Rishikant181/Rettiwt-API#397]
Hi, great work on the library. 

I did mention this many months ago on one of your posts and it was suggested I make an issue. Would you be able to add a method for getting the friendship between 2 users, if it is possible? It would be greatly appreciated. 

[API Docs](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-friendships-show)

**Comment by Rishikant181** [comment]
I'll have to check on this and if it's possible, I'll add it. I'll be looking into it after my semester exams (3 weeks from now). I'll be keeping this issue opened and will work on it later.

Thanks for the feedback!

**Comment by omarcinkonis** [comment]
I did some research on this. Here is the relevant endpoint:
https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-friendships-show

This is a v1.1 endpoint, it might become deprecated eventually. Maybe it already is, I haven't tried using it. Twitter no longer uses this endpoint on its front-end, this endpoint is used instead:
```
https://twitter.com/i/api/graphql/_pnlqeTOtnpbIL9o-fS_pg/ProfileSpotlightsQuery?variables=%7B%22screen_name%22%3A%22elonmusk%22%7D
```

The problem with the new endpoint is that it returns data about the current user + one selected user, instead of friendship between two selected users.

May be relevant - other v1.1 friendship endpoints (post and delete) are used on follow/unfollow via Twitter front-end.

**Comment by Rishikant181** [comment]
@omarcinkonis Thanks for the resources. I'm working on media upload right now (almost done). After that, I'll be working on friendship.

**Comment by Rishikant181** [comment]
Just searched through the endpoints and apparently, no endpoint for getting friendship between two given users is provided to the Twitter Web App.

Will have to look for some alternate "unconventional" solution. I'll keep it posted here.
