### ISSUE TITLE
Login with auth token and not via api key

### ISSUE THREAD

**Issue by Nevgup** [Rishikant181/Rettiwt-API#515]
Hello

I would like know if its possible to login with an auth token cookie, and not via API_KEY from the rettiwt login
I saw that it was possible last year, but not now ?

Thanks for answer !

**Comment by Rishikant181** [comment]
The API_KEY is nothing but the base64 encoded cookie string from the headers obtained after logging in to twitter (and these headers can also be scraped from the browser).

Internally, when you supply the base64 encoded cookies, they are again decoded and combined with an auth token (which is same for all users), to generate the full credentials.

This base64 encoding was done to deal with special characters inside the cookie string as well as make it a bit concise.

**Comment by Nevgup** [comment]
Ok thanks !

**Comment by TheGateKeeper1995** [comment]
Hey how can I bring this back please as I need to authenticate other users, not myself, who are using my site and they have connected their twitter accounts using a bot that saves their oauth_token. I dont want to save their email and password etc, as it's too invasive so I'd just like to log them in using the oauth_token and then they can like and or retweet direct from my website instead of opening a whole other window with an intents link just so they can like and retweet. Thanks in advance

**Comment by BrokedTV** [comment]
Is there any utility to get the api key needed from just the auth token + ct0?

**Comment by Rishikant181** [comment]
@BrokedTV Although no such utility function is exposed from the library itself, but you can write such a function (it's very straight-forward). Take a look at [this](https://github.com/Rishikant181/Rettiwt-API/issues/586#issuecomment-2275541560).

Since you already seem to have the tokens, just execute the code at step 5 from either your code, or from a NodeJS terminal.
