### ISSUE TITLE
How to use rettiwt.tweet.stream and I can't receive tweets

### ISSUE THREAD

**Issue by spencer17x** [Rishikant181/Rettiwt-API#538]
Such as title

**Comment by Rishikant181** [comment]
Did you try the [example](https://rishikant181.github.io/Rettiwt-API/classes/TweetService.html#stream)?

**Comment by spencer17x** [comment]
Yeah, that's what I used as an example

**Comment by spencer17x** [comment]
If I want to get relevant tweets in real time, can I use this api

**Comment by Rishikant181** [comment]
What the `stream` method does is, given a polling rate, it checks if any new tweets are made, if made, it returns the tweets. Note that a tweet is returned only if it's a new one starting from the time the streaming was started.

> If I want to get relevant tweets in real time, can I use this api

So yes, you can. You just need to pass a filter to get the relevant tweets and set a desired polling rate. [Here](https://rishikant181.github.io/Rettiwt-API/classes/TweetFilter.html) are all the filters available.

**Comment by spencer17x** [comment]
Do I need a polling request? Or the request will always return the latest tweet

**Comment by Rishikant181** [comment]
> Do I need a polling request?

The method implicitly does the polling. You just need to call it and iterate over the returned [AsyncGenerator](https://www.javascripttutorial.net/javascript-async-generators/). The example given shows how to do it. The only thing you need to change is instead of `console.log`, do whatever you want with the received tweets.

> Or the request will always return the latest tweet

The request will always return the most recent tweet that was made after the polling started.
