### ISSUE TITLE
Account banned using Rettiwt

### ISSUE THREAD

**Issue by rccar401** [Rishikant181/Rettiwt-API#550]
I'm working on a fairly small project and already have seen accounts get suspended while using rettiwt.tweet.search via node. I've now created 6 burner accounts and generated tokens for each but after a few days of use they get suspended.

I'm not using a proxy or anything like that, which might be causing the issue? It's not at a crazy scale or anything right now, and I haven't been rate limited yet (only banned).

**Comment by Rishikant181** [comment]
Burner accounts, for some reason, are prone to getting suspended easily. I've tested it. But one weird thing is, my permanent accounts work fine, even after all this time. By permanent, I mean the accounts which is intermittently use to access Twitter from a browser. Maybe it's because of the fact that burner account are easy to detect based on the HTTP requests they make. 

I'm trying to find a way to bypass or atleast mask their activity. Any insights will be valuable.

**Comment by rccar401** [comment]
Ahh gotcha, thanks! That makes a ton of sense-- I'll switch over to permanent account and see if that helps. I saw some Reddit posts about fresh accounts getting flagged for ban more often than old accounts, so that's potentially the root cause?

Another quick q-- are you able to sign in via phone number via `npx rettiwt auth login` or is that method for email only?

Love this project btw, thanks for all the work you're doing

**Comment by Rishikant181** [comment]
> I saw some Reddit posts about fresh accounts getting flagged for ban more often than old accounts, so that's potentially the root cause?

I guess yes, atleast that's what has been happening to me throughout my testing. I've been using this with my primary Twitter account with my own name on it, and it's been working consistently without any issues, since the conception of this library.

> are you able to sign in via phone number via npx rettiwt auth login or is that method for email only?

Phone number in place of email should work (assuming 2FA isn't required).

**Comment by Timtendo12** [comment]
> Ahh gotcha, thanks! That makes a ton of sense-- I'll switch over to permanent account and see if that helps. I saw some Reddit posts about fresh accounts getting flagged for ban more often than old accounts, so that's potentially the root cause?
> 
> 
> 
> Another quick q-- are you able to sign in via phone number via `npx rettiwt auth login` or is that method for email only?
> 
> 
> 
> Love this project btw, thanks for all the work you're doing

I know this issue is closed but I wanted to ask if using a permanent account helped for you?

Currently using it in a program that searches for tweets every 60 seconds and it works for 30 minutes but after that the account gets suspended.

I do have 2 other permanent accounts but I don't know if it's worth the risk.

**Comment by Rishikant181** [comment]
@Timtendo12 I have been running a notification polling script using a permanent account, and it seems to be working for quite some time. However, I would still not pass any judgement if it will work for you. All I can say is, I use the account for Rettiwt-API and I also use the same account on a regular basis on Twitter Web and App. So I guess that might have been the reason why Twitter couldn't flag my account as a scraper, since I'm also using it on a regular basis (as a human lol). If the accounts are important to you, it isn't worth the risk.

**Comment by Timtendo12** [comment]
> @Timtendo12 I have been running a notification polling script using a permanent account, and it seems to be working for quite some time. However, I would still not pass any judgement if it will work for you. All I can say is, I use the account for Rettiwt-API and I also use the same account on a regular basis on Twitter Web and App. So I guess that might have been the reason why Twitter couldn't flag my account as a scraper, since I'm also using it on a regular basis (as a human lol). If the accounts are important to you, it isn't worth the risk.

@Rishikant181  Nice, I think it might work on my own account too. I do have some questions.

1. What is your notification polling interval? Is it every 60 seconds or longer?
2. Do you host it on your home network or in the cloud? I raised an issue today about the possibility of my home IP getting banned. My script is also a notification polling script.

**Comment by Rishikant181** [comment]
> What is your notification polling interval? Is it every 60 seconds or longer?

I was polling with an interval of 30 seconds and it crashed out after around 6-7 hours.

> Do you host it on your home network or in the cloud?

It was being polled on a Replit deployement.

> I raised an issue today about the possibility of my home IP getting banned

I don't usually face IP bans since I'm on a dynamic IP connection, with a double NAT.
