### ISSUE TITLE
Tweet from TweetService stream does not included retweetedTweet.

### ISSUE THREAD

**Issue by Timtendo12** [Rishikant181/Rettiwt-API#574]
Hi! 

Whenever I fetch a retweeted tweet using the stream function, it only returns the main tweet and not the retweeted tweet. Could this be because the tweet is quoted? The tweet does have a quoted tweet ID, but isn't it expected that the quoted tweet object would be in the retweetedTweet property? Reposted posts (retweets) are not picked up by the stream.

<img width="1089" alt="image" src="https://github.com/user-attachments/assets/3b43961b-bc25-4261-9aad-043e228c5464">

Tweet:

<img width="598" alt="image" src="https://github.com/user-attachments/assets/1ed22115-d2f5-4a96-ba57-a90fe0e1c0cd">

**Comment by Rishikant181** [comment]
That is not a retweet, it's a quote. That's why the original tweet's id is in the `quotedTweet` property and `retweetedTweet` property is empty. However, a QOL improvement can be made by putting the original tweet object in the `quotedTweet` property, instead of the quoted tweet's id.

A differentiating factor between quote and retweet is, while quoting, you can add your own comments (like in the second picture), which means, in the back-end, you actually create a new tweet which references the original tweet. On the other hand, while retweeting, you don't create a new tweet, you simply share the original tweet.
