### ISSUE TITLE
Cannot read properties of undefined (reading 'rest_id')

### ISSUE THREAD

**Issue by sodamnfoolish** [Rishikant181/Rettiwt-API#626]
hey, looks like sometimes twitter sends invalid response on user.replies.

on 4.1.0 version got `Cannot read properties of undefined (reading 'rest_id')`
on latest one got `One or more validation error(s) occured, check details field.` 
```
[
  ValidationErrorDetails {
    field: 'results',
    constraints: [ 'results must be empty' ]
  }
]
```

found that sometimes tweet.quoted_status_result is `{}` on [this line](https://github.com/Rishikant181/Rettiwt-API/blob/411f4f589b78de9770bb7e3b89bfb5d96b66c263/src/models/data/Tweet.ts#L80)
<img width="368" alt="Screenshot 2024-10-16 at 2 39 55 PM" src="https://github.com/user-attachments/assets/f7e9b6d1-ef95-44d0-9e2d-a439ced01f8d">

**Comment by sodamnfoolish** [comment]
[hot fix base on 4.1.0 version](https://github.com/sodamnfoolish/Rettiwt-API/commit/02b22025719b76214a5cb3fc763fb5de15b95704)

**Comment by Rishikant181** [comment]
Sorry for the late reply.

Thanks for the hotfix. I did discover the cause of the issue, unfortunately, I've been a lot busy lately so couldn't find the time to work on it. I'll try to merge the hotfix from your fork, which will will buy me time for working on a solution.

Thanks for the contribution and feedback. Means a lot.

**Comment by matgott** [comment]
Hey! I'm playing around with this package (thank you btw!) and I'm facing the same problem with the `search` method.

Debugging I found that in the constructor of the `Tweet` class is checking for `tweet.quoted_status_result` to assign the value for `quoted`:

`this.quoted = tweet.quoted_status_result ? new Tweet(tweet.quoted_status_result.result) : undefined;`

But I got a case where `tweet.quoted_status_result` was an empty object `{}` so it was trying to do `new Tweet({})` ending in the previous error because the property `result` wasn't found in `quoted_status_result`:

![image](https://github.com/user-attachments/assets/acec0bd4-7b69-408d-9575-c94a9afe5ca9)

Logs:

```Rettiwt-API] [2024-10-16T19:53:51.362Z] [REQUEST] {"resource":"TWEET_SEARCH","args":{"filter":{"fromUsers":["kalver_juan"]},"count":20,"cursor":"DAADDAABCgABGaCVF4_b0XMKAAIZmIxy-RthNQAIAAIAAAACCAADAAAAAAgABAAAAAsKAAUZoJXslIAnEAoABhmgleyUfitAAAA"}}
[Rettiwt-API] [2024-10-16T19:53:51.363Z] [AUTHORIZATION] {"authenticated":true}
[Rettiwt-API] [2024-10-16T19:53:51.363Z] [VALIDATE] {"target":"FETCH_ARGS"}
[Rettiwt-API] [2024-10-16T19:53:51.363Z] [GET] {"target":"HTTPS_AGENT"}
[Rettiwt-API] [2024-10-16T19:53:51.363Z] [GET] {"target":"USER_CREDENTIAL"}
[Rettiwt-API] [2024-10-16T19:53:52.127Z] [DESERIALIZE] {"id":"1844376999810433054"}
[Rettiwt-API] [2024-10-16T19:53:52.127Z] [DESERIALIZE] {"id":"1844369358476439922"}
[Rettiwt-API] [2024-10-16T19:53:52.127Z] [DESERIALIZE] {"id":"1844364557973848458"}
...\fetch-tweet\node_modules\rettiwt-api\dist\models\data\Tweet.js:21
        this.id = tweet.rest_id;
                        ^

TypeError: Cannot read properties of undefined (reading 'rest_id')```

**Comment by Rishikant181** [comment]
Issue has been fixed. Please upgrade `rettiwt-api` to `v4.1.2`.

**Comment by Rishikant181** [comment]
There was a "Maximum call stack exceeded" error while deserializing tweet(s)  in `v4.1.2`.

Please upgrade to `v4.1.3` instead.
